---
title: "Plots for The Article"
author: "Kadir Korkmaz"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
knit: (function(inputFile, encoding) { 
      workingDir <- '/home/kadir/Desktop/Bitcoin_1MB_Experiments';
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        knit_root_dir = workingDir,
                        output_file=file.path(workingDir, 'remove.pdf')) })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data, include=FALSE}
library(ggplot2)
library(knitr)



throughput_df <- read.csv("throughput_df.csv", header = TRUE)
orphanblock_df <- read.csv("fork_df.csv", header = TRUE)
latency_df <- read.csv("latency_df.csv", header = TRUE)

forkFrequency_df <- read.csv("forks.tsv", header = FALSE, sep = "\t")
colnames(forkFrequency_df)[1] = "BlockSize"
colnames(forkFrequency_df)[2] = "CC"
colnames(forkFrequency_df)[3] = "ExpType"
colnames(forkFrequency_df)[4] = "RoundCount"
colnames(forkFrequency_df)[5] = "L1"
colnames(forkFrequency_df)[6] = "L2"
colnames(forkFrequency_df)[7] = "L3"
colnames(forkFrequency_df)[8] = "L4"
colnames(forkFrequency_df)[9] = "L5"



```


\newpage
## Throughput Plot
\
\
\
```{r throughput, echo=FALSE, fig.height=4, warning=FALSE}

throughput_df$Shape <-paste(throughput_df$ExpType, ifelse(throughput_df$BlockSize == 1000, "1MB", "500KB" ), sep=" ")

pdf(file = "./bitcoin-throughput.pdf",height = 4)

ggplot(throughput_df, aes(x=as.factor(CC), y=Median, group=Shape)) +
  geom_line(aes(linetype=Shape,  color=Shape), lwd=0.3)+
  geom_point(aes(shape=Shape)) +
  scale_shape_manual(values=c(0, 1, 3, 4))+
  guides(linetype = "none", color="none") + 
  theme_bw() +
  theme(legend.position="top") + 
  labs(shape="", x="Cl", y="Median Throughput (KB/Second)")
  
#kable(throughput_df, n=100)

dev.off()
```


\newpage
## Orphan Block Plot
\
\
\
```{r  orphanblocks, echo=FALSE, fig.height=4, warning=FALSE}


orphanblock_df$Shape <-paste(orphanblock_df$ExpType, ifelse(orphanblock_df$BlockSize == 1000000, "1MB", "500KB" ), sep=" ")

pdf(file = "./bitcoin-discardeddata.pdf",height = 4)

ggplot(orphanblock_df, aes(x=as.factor(CC), y=ExtraCostPercent, group=Shape)) +
  geom_line(aes(linetype=Shape, color=Shape), lwd=0.3)+
  geom_point(aes(shape=Shape)) +
  scale_shape_manual(values=c(0, 1, 3, 4))+
  guides(linetype = "none", color="none") + 
  theme_bw() +
  theme(legend.position="top") + 
  labs(shape="", x="Cl", y="Discarded Data Percent Per Round")

dev.off()

#kable(orphanblock_df)

```


\newpage
## Latency Plot
\
\
\
```{r latency, echo=FALSE, fig.height=4, warning=FALSE}

latency_df$Shape <-paste(latency_df$ExpType, ifelse(latency_df$BlockSize == 1000000, "1MB", "500KB" ), sep=" ")

pdf(file = "./bitcoin-roundcompletion.pdf",height = 4)

ggplot(latency_df, aes(x=as.factor(CC), y=Median, group=Shape)) +
  geom_line(aes(linetype=Shape,  color=Shape), lwd=0.3)+
  geom_point(aes(shape=Shape)) +
  scale_shape_manual(values=c(0, 1, 3, 4))+
  guides(linetype = "none", color="none") + 
  theme_bw() +
  theme(legend.position="top") + 
  labs(shape="", x="Cl", y="Round Completion Time (Seconds)")
  
kable(latency_df, n=100)

dev.off()
```

\newpage
## Fork Distribution
\
\
\
```{r  forkdistribution, echo=FALSE, fig.height=4, warning=FALSE}

kable(forkFrequency_df)

forkFrequency_df$Shape <-paste(forkFrequency_df$ExpType, ifelse(forkFrequency_df$BlockSize == 1000000, "1MB", "500KB" ), sep=" ")


#kable(orphanblock_df)

```
