---
title: "Bitcoin++ vs Bitcoin with Reduced Difficulty Statistics"
author: "Kadir Korkmaz"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
knit: (function(inputFile, encoding) { 
      workingDir <- '/home/kadir/Desktop/Bitcoin_1MB_Experiments';
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        knit_root_dir = workingDir,
                        output_file=file.path(workingDir, 'experiment-report.pdf')) })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data, include=FALSE}
library(dplyr)
library(ggplot2)
library(knitr)
library(tibble)
library(readr)


experimentDF <- read.table('experiment.stats', sep = '\t',header = FALSE)


colnames(experimentDF) <- c( "BlockSize", "CC", "Difficulty",  "NodeID","Round","Type","ElapsedTime", "BlockHash")


printSummaryStats <- function(df, column) {
  summ <- df %>% summarise(min = min(column), mean= mean(column), sd= sd(column), max = max(column))
  kable(summ)
}

printConfidenceInterval <- function(column) {
  r <- CI(column, ci=0.95)
  kable(r)
}


printMeanBarChart <- function(df){
    
  grouped_df <- df %>% 
                  group_by(BlockSize, CC ) %>%
                  summarise(
                    Min = min(ElapsedTime),
                    Q1 = quantile(ElapsedTime, 0.25),
                    Median = median(ElapsedTime),
                    Mean = mean(ElapsedTime),
                    Q3 = quantile(ElapsedTime, 0.75),
                    Max = max(ElapsedTime),
                    SD =sd(ElapsedTime)
                  )
  
  p <- ggplot(grouped_df, aes(x=BlockSize, y=Mean, group=CC, color=factor(CC))) +
    geom_line(aes( linetype=factor(CC), color=factor(CC) ))+
    geom_point() +
    labs( x = "Macro Block Size (MB)", y = "Mean Elapsed Time (ms)", color = "CC", linetype="CC" )+
    theme(legend.position="top",legend.box="vertical", legend.margin=margin())+
    scale_x_continuous(labels = as.character(grouped_df$BlockSize), breaks = grouped_df$BlockSize)
  
  
  
  t <- kable(grouped_df, n=100)

  return( list("plot" = p , "table" = t ))
}


calculateSummaryStats <-function(df){
  
    summary_stats_df <- df %>% 
                  group_by(ExpType,BlockSize, CC ) %>%
                  summarise(
                    Min = min(ElapsedTime),
                    Q1 = quantile(ElapsedTime, 0.25),
                    Median = median(ElapsedTime),
                    Mean = mean(ElapsedTime),
                    Q3 = quantile(ElapsedTime, 0.75),
                    Max = max(ElapsedTime),
                    SD =sd(ElapsedTime)
                  )
    
    
  return(summary_stats_df)
}


plot_histogram <- function(df){
  
  ggplot(df, aes(x=ElapsedTime))+
  geom_histogram(color="darkblue", fill="lightblue")

}


```


```{r, echo=FALSE, warning=FALSE}
#TODO: add explanation
BitcoinPP <- "Bitcoin++"
BitcoinReducedDiff <- "BitcoinReducedDiff"
experimentDF <-  experimentDF %>% add_column( ExpType=if_else(experimentDF$Difficulty == 600, BitcoinPP, BitcoinReducedDiff))
#TODO: add explanation
experimentDF <- experimentDF %>% mutate(CC=if_else(experimentDF$Difficulty == 600, experimentDF$CC, as.integer( 600 / experimentDF$Difficulty) ))

########################################################
##experimentDF <- experimentDF %>% filter(Round < 320)##


blockReceivedDF <- experimentDF %>% filter(Type == "BLOCK_RECEIVED")
hopCountDF <- experimentDF %>% filter(Type == "HOP_COUNT")
processingTimeDF <- experimentDF %>% filter(Type == "PROCESSING_TIME")
endOfRound <-experimentDF %>% filter(Type == "END_OF_ROUND")
# This is to calculate the second version of throughput
endOfRound2 <-data.frame(endOfRound)


throughputDF <- experimentDF %>% filter(Type == "END_OF_ROUND")
throughputDF$ElapsedTime <- throughputDF$ElapsedTime / 1000 # elapsed time in seconds
throughputDF$BlockSize <- throughputDF$BlockSize / 1000 # block size in KB

#Calculates throughput
throughputDF <- throughputDF %>% mutate(Throughput=if_else(throughputDF$Difficulty == 600, throughputDF$BlockSize * throughputDF$CC / throughputDF$ElapsedTime, throughputDF$BlockSize / throughputDF$ElapsedTime ))
#throughputDF$Throughput <- throughputDF$BlockSize * throughputDF$CC / throughputDF$ElapsedTime

```

\newpage

### Configuration
```{r, echo=FALSE, comment=''}
#https://stackoverflow.com/questions/29257985/r-markdown-how-do-i-show-file-contents

# Reads configuration file to print
if (file.exists("Configuration.txt")){
  experimentConfiguration <- read_file('Configuration.txt')  
}
cat(experimentConfiguration)
```



\newpage
## Round Latency

```{r, echo=FALSE, fig.height=4, warning=FALSE}



endOfRound$ElapsedTime <- endOfRound$ElapsedTime / 1000
#endOfRound$Type[data$Difficulty!=600] <- "ClassicBitcoin"

#https://www.r-graph-gallery.com/265-grouped-boxplot-with-ggplot2.html
#https://www.r-graph-gallery.com/223-faceting-with-ggplot2.html
ggplot(endOfRound, aes(x=as.factor(CC), y=ElapsedTime )) + 
    geom_boxplot(fill="slateblue", alpha=0.2) + 
    xlab("ConcurrencyConstant") +
    ylab("Round Latency(ms)") +
    scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) +
    facet_wrap(~ExpType)


grouped_endOfRound <- endOfRound %>% 
                group_by(ExpType,BlockSize, CC ) %>%
                summarise(
                  Min = min(ElapsedTime),
                  Q1 = quantile(ElapsedTime, 0.25),
                  Median = median(ElapsedTime),
                  Mean = mean(ElapsedTime),
                  Q3 = quantile(ElapsedTime, 0.75),
                  Max = max(ElapsedTime)
                )
kable(grouped_endOfRound, n=100)
```


<!-- \newpage -->
<!-- ## Throughput -->

<!-- ```{r, echo=FALSE, fig.height=4, warning=FALSE} -->

<!-- grouped_throughputDF <- throughputDF %>%  -->
<!--                 group_by( ExpType, CC ) %>% -->
<!--                 summarise( -->
<!--                   Min = min(Throughput), -->
<!--                   Q1 = quantile(Throughput, 0.25), -->
<!--                   Median = median(Throughput), -->
<!--                   Mean = mean(Throughput), -->
<!--                   Q3 = quantile(Throughput, 0.75), -->
<!--                   Max = max(Throughput) -->
<!--                 ) -->

<!-- grouped_throughputDF$MedianRounded <- signif(grouped_throughputDF$Median, digits = 3)  -->

<!-- ggplot(throughputDF, aes(x=as.factor(CC), y=Throughput)) + -->
<!--     geom_boxplot(fill="slateblue", alpha=0.2) + -->
<!--     #geom_text(data =grouped_throughputDF, aes(x=as.factor(CC), y = MedianRounded, label = MedianRounded), size = 2.8, vjust = 0.3, hjust = 2.5) + -->
<!--     xlab("ConcurrencyConstant") + -->
<!--     ylab("Throughput (KB/S)") + -->
<!--     facet_wrap(~ExpType) -->
<!--     #+scale_y_continuous(limits = quantile(throughputDF$Throughput, c(0.1, 0.9)), labels = function(x) format(x, scientific = FALSE)) -->




<!-- kable(grouped_throughputDF, n=100) -->
<!-- ``` -->

\newpage
## Throughput

```{r, echo=FALSE, fig.height=4, warning=FALSE}


throughputDF <- endOfRound2 %>% group_by( ExpType, Difficulty, BlockSize, CC, NodeID )%>%
                summarise(
                  RoundCount=n(),
                  TotalTime=sum(ElapsedTime)
                )

throughputDF$TotalTime <- throughputDF$TotalTime  / 1000
throughputDF$BlockSize <- throughputDF$BlockSize  / 1000


throughputDF <- throughputDF %>% mutate(
  Throughput=if_else(Difficulty == 600, 
                     BlockSize * CC * RoundCount / TotalTime, 
                     BlockSize * RoundCount / TotalTime )
  )


grouped_throughputDF <- throughputDF %>% 
                group_by( ExpType, CC ) %>%
                summarise(
                  Min = min(Throughput),
                  Q1 = quantile(Throughput, 0.25),
                  Median = median(Throughput),
                  Mean = mean(Throughput),
                  Q3 = quantile(Throughput, 0.75),
                  Max = max(Throughput)
                )

grouped_throughputDF$MedianRounded <- signif(grouped_throughputDF$Median, digits = 3) 

ggplot(throughputDF, aes(x=as.factor(CC), y=Throughput)) +
    geom_boxplot(fill="slateblue", alpha=0.2) +
    #geom_text(data =grouped_throughputDF, aes(x=as.factor(CC), y = MedianRounded, label = MedianRounded), size = 2.8, vjust = 0.3, hjust = 2.5) +
    xlab("ConcurrencyConstant") +
    ylab("Throughput (KB/S)") +
    expand_limits(x = 0, y = 0)+
    facet_wrap(~ExpType)
    #+scale_y_continuous(limits = quantile(throughputDF$Throughput, c(0.1, 0.9)), labels = function(x) format(x, scientific = FALSE))




kable(grouped_throughputDF, n=100)

```


\newpage
## Average number of Delivered Blocks per Round (Fork statistics)
```{r, echo=FALSE, fig.height=4, warning=FALSE}

#blockReceivedDF %>% count(BlockSize, CC, Round, NodeID)

block_count_df <- blockReceivedDF %>% 
                    count(ExpType,BlockSize, CC, Round, NodeID) %>% 
                          group_by( BlockSize, CC, ExpType  ) %>%
                            summarise(
                              MeanBlockCount = mean(n)
                            )




ggplot(block_count_df, aes(fill=factor(CC), y=factor(MeanBlockCount), x=factor(BlockSize))) + 
    geom_bar(position="dodge", stat="identity")+
    facet_wrap(~ExpType)


block_count_df <- block_count_df %>% mutate(ExtraCostPercent=if_else(ExpType == BitcoinPP, (MeanBlockCount - CC)*100/CC, (MeanBlockCount - 1)*100 ))


kable(block_count_df)

# cdf <- blockReceivedDF %>% count(ExpType,BlockSize, CC, NodeID) %>% group_by( ExpType,BlockSize, CC, n  ) %>% count()
# names(cdf)[4]<-"BlockCount"
# names(cdf)[5]<-"NodeCount"
# kable(cdf)


```

\newpage
## Number of rounds a single block decided

```{r, echo=FALSE}

grouped_endOfRound <- endOfRound %>% 
                group_by(ExpType,BlockSize, CC, Round ) %>%
                summarise(
                  DecidedBlockCount = n_distinct(BlockHash)
                ) %>% group_by(ExpType,BlockSize, CC ) %>%
                summarise(
                  SingleBlockDecidedRoundCount=sum(DecidedBlockCount==1)
                )

max_rounds  <-  endOfRound %>% 
                group_by(ExpType,BlockSize, CC ) %>%
                summarise(
                  MaxRound = max(Round)
                )


kable(max_rounds, n=100)

kable(grouped_endOfRound, n=100)
```

\newpage
## Block Dissemination Time

```{r, echo=FALSE, fig.height=4, warning=FALSE}

#plot_histogram(blockReceivedDF)
kable( calculateSummaryStats(blockReceivedDF) )

```


\newpage
## Block Hop Count

```{r, echo=FALSE, fig.height=4, warning=FALSE}

#plot_histogram(hopCountDF)
kable( calculateSummaryStats(hopCountDF) )


```



<!-- \newpage -->
<!-- ## Bug -->
<!-- ```{r, echo=FALSE, fig.height=4, warning=FALSE} -->

<!-- blockReceivedDF_bug <- processingTimeDF %>% filter(ElapsedTime > 20000) %>% select(NodeID,Round,Type,ElapsedTime) -->

<!-- head(blockReceivedDF_bug, n=100) -->


<!-- ``` -->
